dist: focal

language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-9
      - cmake

script:
- cd ${TRAVIS_BUILD_DIR}
- mkdir build
- cd build
- CXX=/usr/bin/g++-9 cmake -D NLPP_BUILD_TESTS=ON ..
- make tests -j4
- ./tests/nlpp_tests

after_success:
- bash <(curl -s https://codecov.io/bash)

notifications:
  email: false