dist: trusty
sudo: required

language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - cmake

script:
- cd ${TRAVIS_BUILD_DIR}
- mkdir build
- cd build
- CXX=/usr/bin/g++-7 cmake .. -DNLPP_INCLUDE_INSTALL_DIR=${TRAVIS_BUILD_DIR}/build -DEIGEN_INCLUDE_LOCAL=ON
- make tests -j4
- ./tests/tests

after_success:
- bash <(curl -s https://codecov.io/bash)

notifications:
  email: false